version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
        ports:
          - 5432:5432
        volumes:
          - ./etl_home_ora/bin/initial/database_user.sql:/docker-entrypoint-initdb.d/database_user.sql
          - ./etl_home_ora/bin/initial/dwh_tables.sql:/docker-entrypoint-initdb.d/dwh_tables.sql
          - ./etl_home_ora/bin/initial/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql
          #- ./etl_home_ora/etl_base/sql/DEMO-MERGE.ddl:/docker-entrypoint-initdb.d/DEMO-MERGE.ddl
          #- ./etl_home_ora/bin/initial/SQLG-WRAPUP.sql:/docker-entrypoint-initdb.d/SQLG-WRAPUP.sql
    webserver:
        image: jessewei/sqlg-airflow:latest
        restart: always
        depends_on:
          - postgres
        environment:
          - TZ=Asia/Taipei
          #- LOAD_EX=n
          - EXECUTOR=Local
          - AIRFLOW__CORE__FERNET_KEY=xfaECYb20a2PzNTcIYXFXztTlaEVD43KwUoXeer_83k=
          - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
          #- AIRFLOW__WEBSERVER__RBAC=False
          
        volumes:
          #- ./dags:/usr/local/airflow/dags
          - ./etl_home_ora/etl_base/dags:/usr/local/airflow/dags
          - ./etl_home_ora/etl_base/sql:/usr/local/airflow/sql
          - ./etl_home_ora/bin:/usr/local/airflow/bin
          - ./etl_home_ora/logs:/usr/local/airflow/logs
          - ./etl_home_ora/etl_base/requirements.txt:/requirements.txt
        ports:
          - 8080:8080
        command: webserver
                    
        #command: airflow variables -s sql_path "/usr/local/airflow/sql"
                         
                        
                      


